version: '3'

services:
  memoir-cpython:
    build:
      context: .
      args:
      - PYTHON_IMAGE=${CPYTHON_IMAGE_NAME}
      - PYTHON_IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/memoir-cpython:0.0.0
    volumes:
      - ./memoir/:/opt/memoir/memoir/
      - ./tests/:/opt/memoir/tests/
      - ./README.md:/opt/memoir/README.md
      - ./setup.py:/opt/memoir/setup.py
      - ./setup.cfg:/opt/memoir/setup.cfg
    entrypoint: python3
    command: setup.py test
